<!DOCTYPE html>
<html lang="en">
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<title>Byzantium</title>
		<link rel="shortcut icon" href="img/favicon.png" type="image/x-icon">
		<link rel="stylesheet" href="libs/font-awesome/css/font-awesome.min.css">
		<link rel="stylesheet" href="css/libs.min.css">
		<link rel="stylesheet" href="css/main.css">
	</head>
	<body class="main-page">
		<div class="wrapper">
			<header class="header">
				<div class="header-wrap">
					<a href="/" class="header-logo">
						<img src="img/logo-company.png" alt="logo-company.png">
					</a>
					<div class="nav-text">
						<a href="#" class="become-sponsor-link">Become a sponsor</a>
						<a href="#" class="use-my-code-link btn-green btn-small">Request an invite</a>
					</div>
				</div>

				<div class="back-link-wrap">
					<div class="back-link-inner">
						<a href="" class="back-link">
							<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 240.823 240.823" style="enable-background:new 0 0 240.823 240.823;" xml:space="preserve">
								<path d="M57.633,129.007L165.93,237.268c4.752,4.74,12.451,4.74,17.215,0c4.752-4.74,4.752-12.439,0-17.179
									l-99.707-99.671l99.695-99.671c4.752-4.74,4.752-12.439,0-17.191c-4.752-4.74-12.463-4.74-17.215,0L57.621,111.816
									C52.942,116.507,52.942,124.327,57.633,129.007z"/>
							</svg>
							<span>Back</span>
						</a>
					</div>
				</div>

			</header>
			<main class="main">
				<div class="container">
					<div class="main-content terms-of-use-page">
						<div class="page-title">Privacy Policy
							<span class="terms-of-use-title-decor-privce"><img src="img/svg/green_circle.svg" alt=""></span>
							<img src="img/svg/green_cross.svg" alt="green-cross" class="terms-use-decor-cross-1-privce">
						</div>
						<div class="page-content">
							<div class="page-block">
								<div class="page-block-title">INTRODUCTION</div>
								<p class="page-block-text">
									Effective date: June 25, 2018
								</p>
							</div>
							<div class="page-block">
								<div class="page-block-title">BYZANTIUM RENAISSANCE LP ("us", "we", or "our") operates the https://top10.bzntm.com website (the "Service").</div>
								<p class="page-block-text">
									This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that 	data.
								</p>
								<p class="page-block-text">
									We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. This policy affects your legal rights and obligations so please read it carefully.
								</p>
							</div>
							<div class="page-block">
								<div class="page-block-title">DEFINITIONS</div>
								<img src="img/svg/green_cross.svg" alt="green-cross" class="terms-use-decor-cross-2-privce">
								<ul>
									<li>
										<div class="page-block-title tac">Service</div>
										<p class="page-block-text">
											Service is the https://top10.bzntm.com website operated by BYZANTIUM RENAISSANCE LP, International House, 38 Thistle Street, Edinburgh, Scotland, EH2 1EN
										</p>
									</li>
									<li>
										<div class="page-block-title tac">Personal Data</div>
										<p class="page-block-text">
											Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
										</p>
									</li>
									<li>
										<div class="page-block-title tac">Usage Data</div>
										<p class="page-block-text">
											Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
										</p>
									</li>
									<li>
										<div class="page-block-title tac">Cookies</div>
										<p class="page-block-text">
											Cookies are small pieces of data stored on your device (computer or mobile device).
										</p>
									</li>
									<li>
										<div class="page-block-title tac">Data Controller</div>
										<p class="page-block-text">
											Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed.
											For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.
										</p>
									</li>
									<li>
										<div class="page-block-title tac">Data Processors (or Service Providers)</div>
										<p class="page-block-text">
											Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller.
											We may use the services of various Service Providers in order to process your data more effectively.
										</p>
									</li>
									<li>
										<div class="page-block-title tac">Data Subject (or User)</div>
										<p class="page-block-text">
											Data Subject is any living individual who is using our Service and is the subject of Personal Data.
										</p>
									</li>
								</ul>
							</div>
							<div class="page-block">
								<div class="page-block-title">INFORMATION COLLECTION AND USE</div>
								<p class="page-block-text">
									We collect several different types of information for various purposes to provide and improve our Service to you.
								</p>
							</div>
							<div class="page-block">
								<div class="page-block-title">TYPES OF DATA COLLECTED</div>
							</div>
							<div class="page-block">
							<div class="decor-wave-one-privce">
								<img src="img/svg/white_wave.svg" alt="">
							</div>
								<div class="page-block-title tac">Personal Data</div>
								<p class="page-block-text">
									While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
								</p>
								<p class="page-block-text">Email address</p>
								<p class="page-block-text">First name and last name</p>
								<p class="page-block-text">Phone number</p>
								<p class="page-block-text">Cookies and Usage Data</p>
								<p class="page-block-text">We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send or by contacting us</p>
							</div>
							<div class="page-block">
								<div class="page-block-title tac">Usage Data</div>
								<p class="page-block-text">
									We may also collect information how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
								</p>
							</div>
							<div class="page-block">
								<div class="page-block-title tac">Tracking Cookies Data</div>
								<p class="page-block-text">We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.</p>
								<p class="page-block-text">Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.</p>
								<p class="page-block-text">You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
								<p class="page-block-text">Examples of Cookies we use:</p>
								<p class="page-block-text"><u>Session Cookies</u>. We use Session Cookies to operate our Service.</p>
								<p class="page-block-text"><u>Preference Cookies</u>. We use Preference Cookies to remember your preferences and various settings.</p>
								<p class="page-block-text"><u>Security Cookies.</u> We use Security Cookies for security purposes.</p>
							</div>
							<div class="page-block">
								<img src="img/svg/green_cross.svg" alt="green-cross" class="terms-use-decor-cross-3-privce">
								<div class="page-block-title">USE OF DATA</div>
								<p class="page-block-text">BYZANTIUM RENAISSANCE LP uses the collected data for various purposes:</p>
								<p class="page-block-text">To provide and maintain our Service</p>
								<p class="page-block-text">To notify you about changes to our Service</p>
								<p class="page-block-text">To allow you to participate in interactive features of our Service when you choose to do so</p>
								<p class="page-block-text">To provide customer support</p>
								<p class="page-block-text">To gather analysis or valuable information so that we can improve our Service</p>
								<p class="page-block-text">To monitor the usage of our Service</p>
								<p class="page-block-text">To detect, prevent and address technical issues</p>
								<p class="page-block-text">To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</p>
							</div>
							<div class="page-block">
								<div class="decor-wave-three-privce">
									<img src="img/svg/white_wave.svg" alt="">
									<img src="img/svg/white_wave.svg" alt="">
									<img src="img/svg/white_wave.svg" alt="">
								</div>
								<div class="page-block-title">LEGAL BASIS FOR PROCESSING PERSONAL DATA UNDER GENERAL DATA PROTECTION REGULATION (GDPR)</div>
								<p class="page-block-text">If you are from the European Economic Area (EEA), BYZANTIUM RENAISSANCE LP legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.</p>
								<p class="page-block-text">We need to perform a contract with you</p>
								<p class="page-block-text">You have given us permission to do so</p>
								<p class="page-block-text">The processing is in our legitimate interests and it's not overridden by your rights</p>
								<p class="page-block-text">For payment processing purposes</p>
								<p class="page-block-text">To comply with the law</p>
							</div>
							<div class="page-block">
								<div class="page-block-title">RETENTION OF DATA</div>
								<p class="page-block-text">BYZANTIUM RENAISSANCE LP will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
								<p class="page-block-text">BYZANTIUM RENAISSANCE LP will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>
							</div>
							<div class="page-block">
								<div class="page-block-title">TRANSFER OF DATA</div>
								<p class="page-block-text">Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</p>
								<p class="page-block-text">BYZANTIUM RENAISSANCE LP will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>
							</div>
							<div class="page-block">
								<div class="page-block-title">DISCLOSURE OF DATA</div>
							</div>
							<div class="page-block">
								<div class="page-block-title">DISCLOSURE FOR LAW ENFORCEMENT</div>
								<p class="page-block-text">Under certain circumstances, BYZANTIUM RENAISSANCE LP may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
							</div>
							<div class="page-block">
								<div class="page-block-title">LEGAL REQUIREMENTS</div>
								<p class="page-block-text">BYZANTIUM RENAISSANCE LP may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
								<p class="page-block-text">To comply with a legal obligation</p>
								<p class="page-block-text">To protect and defend the rights or property of BYZANTIUM RENAISSANCE LP</p>
								<p class="page-block-text">To prevent or investigate possible wrongdoing in connection with the Service</p>
								<p class="page-block-text">To protect the personal safety of users of the Service or the public</p>
								<p class="page-block-text">To protect against legal liability</p>
							</div>
							<div class="page-block">
								<img src="img/svg/green_cross.svg" alt="green-cross" class="terms-use-decor-cross-4-privce">

								<div class="page-block-title">SECURITY OF DATA</div>
								<p class="page-block-text">The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
							</div>
							<div class="page-block">
								<div class="page-block-title">"DO NOT TRACK" SIGNALS UNDER CALIFORNIA ONLINE PRIVACY PROTECTION ACT (CALOPPA)</div>
								<p class="page-block-text">We do not support Do Not Track ("DNT"). Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.</p>
								<p class="page-block-text">You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.</p>
							</div>
							<div class="page-block">
								<div class="page-block-title">YOUR DATA PROTECTION RIGHTS UNDER GENERAL DATA PROTECTION REGULATION (GDPR)</div>
								<p class="page-block-text">If you are a resident of the European Economic Area (EEA), you have certain data protection rights. BYZANTIUM RENAISSANCE LP aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.</p>
								<p class="page-block-text">If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.</p>
								<p class="page-block-text">In certain circumstances, you have the following data protection rights:</p>
								<p class="page-block-text"><u>The right to access, update or to delete the information we have on you.</u> Whenever made possible, you can access, update or request deletion of your Personal Data directly within your account settings section. If you are unable to perform these actions yourself, please contact us to assist you.</p>
								<p class="page-block-text"><u>The right of rectification.</u> You have the right to have your information rectified if that information is inaccurate or incomplete.</p>
								<p class="page-block-text"><u>The right to object.</u> You have the right to object to our processing of your Personal Data.</p>
								<p class="page-block-text"><u>The right of restriction.</u> You have the right to request that we restrict the processing of your personal information.</p>
								<p class="page-block-text"><u>The right to data portability.</u> You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.</p>
								<p class="page-block-text"><u>The right to withdraw consent.</u> You also have the right to withdraw your consent at any time where BYZANTIUM RENAISSANCE LP relied on your consent to process your personal information.</p>
								<p class="page-block-text">Please note that we may ask you to verify your identity before responding to such requests.</p>
								<p class="page-block-text">You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).</p>
							</div>
							<div class="page-block">
								<div class="page-block-title">SERVICE PROVIDERS</div>
								<p class="page-block-text">We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.</p>
								<p class="page-block-text">These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>
							</div>
							<div class="page-block">
								<div class="page-block-title">ANALYTICS</div>
								<p class="page-block-text">We may use third-party Service Providers to monitor and analyze the use of our Service.</p>
								<ul>
									<li>
										<div class="page-block-title tac">Google Analytics</div>
										<p class="page-block-text">Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.</p>
										<p class="page-block-text">You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing information with Google Analytics about visits activity.</p>
										<p class="page-block-text">For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: https://policies.google.com/privacy?hl=en</p>
										<p class="page-block-text"></p>
										<p class="page-block-text"></p>
									</li>
									<li>
										<div class="page-block-title tac">GetResponse</div>
										<p class="page-block-text">GetResponse is an online marketing / web analytics service offered by GetResponse Sp. z o.o.  For more information on the privacy practices of GetResponse Sp. z o.o., please visit the GetResponse privacy policy web page: https://www.getresponse.co.uk/email-marketing/gb-legal/privacy.html?lang=gb&_ga=2.204388176.1514581265.1529922092-1861378050.1529922092</p>		
									</li>
									<li>
										<div class="page-block-title tac">Hotjar</div>
										<p class="page-block-text">
											Hotjar is an online marketing / web analytics service offered by Hotjar Ltd. For more information on the privacy practices of Hotjar Ltd., please visit the Hotjar privacy policy web page: https://www.hotjar.com/legal/policies/privacy
										</p>
									</li>
									<li>
										<div class="page-block-title tac">Ticket Tailor</div>
										<p class="page-block-text">
											Ticket Tailor is an online ticket-selling service offered by Zimma Ltd. For more information on the privacy practices of Ticket Tailor, please visit the Ticket Tailor privacy policy web page:  https://www.tickettailor.com/privacy-policy/"
										</p>
									</li>
								</ul>
							</div>
							<div class="page-block">
								<div class="page-block-title">BEHAVIORAL REMARKETING</div>
								<p class="page-block-text">BYZANTIUM RENAISSANCE LP uses remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimize and serve ads based on your past visits to our Service.</p>
								<ul>
									<li>
										<div class="page-block-title tac">Google AdWords</div>
										<p class="page-block-text">
											Google AdWords remarketing service is provided by Google Inc. You can opt-out of Google Analytics for Display Advertising and customize the Google Display Network ads by visiting the Google Ads Settings page: http://www.google.com/settings/ads
										</p>
										<p class="page-block-text">Google also recommends installing the Google Analytics Opt-out Browser Add-on - https://tools.google.com/dlpage/gaoptout - for your web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability to prevent their data from being collected and used by Google Analytics.</p>
										<p class="page-block-text">For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: https://policies.google.com/privacy?hl=en</p>
									</li>
									<li>
										<div class="page-block-title tac">Facebook</div>
										<p class="page-block-text">Facebook remarketing service is provided by Facebook Inc.</p>
										<p class="page-block-text">You can learn more about interest-based advertising from Facebook by visiting this page: https://www.facebook.com/help/164968693837950</p>
										<p class="page-block-text">To opt-out from Facebook's interest-based ads follow these instructions from Facebook: https://www.facebook.com/help/568137493302217</p>
										<p class="page-block-text">Facebook adheres to the Self-Regulatory Principles for Online Behavioral Advertising established by the Digital Advertising Alliance. You can also opt-out from Facebook and other participating companies through the Digital Advertising Alliance in the USA http://www.aboutads.info/choices/, the Digital Advertising Alliance of Canada in Canada http://youradchoices.ca/ or the European Interactive Digital Advertising Alliance in Europe http://www.youronlinechoices.eu/, or opt-out using your mobile device settings.</p>
										<p class="page-block-text">For more information on the privacy practices of Facebook, please visit Facebook's Data Policy: https://www.facebook.com/privacy/explanation</p>
									</li>
								</ul>
							</div>
							<div class="page-block">
								<img src="img/svg/green_cross.svg" alt="green-cross" class="terms-use-decor-cross-3-privce">
								<div class="page-block-title">PAYMENTS</div>
									<p class="page-block-text">We may provide paid products and/or services within the Service. In that case, we use third-party services for payment processing (e.g. payment processors).</p>
									<p class="page-block-text">We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.</p>
									<p class="page-block-text">The payment processors we work include PayPal. Their Privacy Policy can be viewed at https://www.paypal.com/webapps/mpp/ua/privacy-full</p>
									<p class="page-block-text">We also accept bitcoin payments.</p>
							</div>
							<div class="page-block">
								<div class="page-block-title">LINKS TO OTHER SITES</div>
								<p class="page-block-text">Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
								<p class="page-block-text">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
							</div>
							<div class="page-block">
								<div class="page-block-title">CHILDREN'S PRIVACY</div>
								<p class="page-block-text">Our Service does not address anyone under the age of 18 ("Children").</p>
								<p class="page-block-text">We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>
							</div>
							<div class="page-block">
								<div class="page-block-title">CHANGES TO THIS PRIVACY POLICY</div>
								<p class="page-block-text">We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
								<p class="page-block-text">We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.</p>
								<p class="page-block-text">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
							</div>
							<div class="page-block">
								<div class="page-block-title">APPLICABLE LAW / DISPUTE RESOLUTION</div>
								<p class="page-block-text">This Policy shall be governed by and construed in accordance with the law of Scotland, and you agree to submit to the exclusive jurisdiction of the Scottish Courts.</p>
							</div>
							<div class="page-block">
								<img src="img/svg/white_cross.svg" alt="green-cross" class="terms-use-decor-cross-5-privce">
								<div class="page-block-title">CONTACT US</div>
								<p class="page-block-text">If you have any questions about this Privacy Policy, please contact us:</p>
								<p class="page-block-text">By email: top10@bznt.com</p>
							</div>
						</div>
						<div class="statue-block">
							<div class="statue-block-img">
							<img src="img/statue_lion3.png" alt="" class="statue-block-img3">
						</div>
						</div>
					</div>
				</div>
      <div class="soc-wrap privecy">
        <a href="#" class="soc-wrap-link js-contact-us">
         <span class="soc-wrap-img"><?php include('img/svg/email_icon.svg') ?></span>
         <!-- <img src="img/svg/email_icon.svg" alt="" class="soc-wrap-img"> -->
       </a>
       <a href="t.me/top10pointoftrust" class="soc-wrap-link">
         <span class="soc-wrap-img-sc"><?php include('img/svg/telegram_icon.svg') ?></span>
         <!-- <img src="img/svg/telegram_icon.svg" alt="" class=" soc-wrap-img-sc"> -->
       </a>
       <a href="twitter.com/top10_of_trust" class="soc-wrap-link">
         <span class="soc-wrap-img-th"><?php include('img/svg/twitter_icon.svg') ?></span>
         <!-- <img src="img/svg/twitter_icon.svg" alt="" class=" soc-wrap-img-th"> -->
       </a>
       <a href="facebook.com/top10pointoftrust" class="soc-wrap-link">
         <span class="soc-wrap-img-ft"><?php include('img/svg/facebook_icon.svg') ?></span>
         <!-- <img src="img/svg/facebook_icon.svg" alt="" class=" soc-wrap-img-ft"> -->
       </a>
     </div>
			</main>
		</div>
		<!-- modal -->
		<div class="modal get-invite-modal">
			<button class="close-modal js-close-modal">
				<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 612 612" style="enable-background:new 0 0 612 612;" xml:space="preserve">
					<g>
						<polygon points="612,36.004 576.521,0.603 306,270.608 35.478,0.603 0,36.004 270.522,306.011 0,575.997 35.478,611.397 306,341.411 576.521,611.397 612,575.997 341.459,306.011"/>
					</g>
				</svg>
			</button>
			<div class="decor-cross">
				<img src="img/many_cross.png" alt="">
			</div>
			<div class="inner-container get-invite-inner">
				<div class="modal-content">
					<div class="modal-title">Get an Invite</div>
					<div class="modal-pre-text">Leave your information below and we’ll proceed your request as soo as we can.</div>
					<form action="" class="modal-form">
						<div class="modal-form-row get-invite-modal-row">
							<span class="modal-form-input-title">Name</span>
							<input type="text" class="modal-form-input">
						</div>
						<div class="modal-form-row get-invite-modal-row">
							<span class="modal-form-input-title">Last Name</span>
							<input type="text" class="modal-form-input">
						</div>
						<div class="modal-form-row get-invite-modal-row">
							<span class="modal-form-input-title">Email</span>
							<input type="text" class="modal-form-input">
						</div>
						<div class="modal-form-row get-invite-modal-row">
							<span class="modal-form-input-title">Company</span>
							<input type="text" class="modal-form-input">
						</div>
						<div class="modal-form-row get-invite-modal-row">
							<span class="modal-form-input-title">Title</span>
							<input type="text" class="modal-form-input">
						</div>
						<div class="modal-form-row get-invite-modal-row">
							<span class="modal-form-input-title">Message</span>
							<input type="text" class="modal-form-input">
						</div>
						<button type="submit" class="btn-green-2">Send request</button>
					</form>
				</div>
				<img src="img/statue_lion.png" alt="Byzantium #Lion">
			</div>
		</div>
		<!-- modal -->
		<div class="modal become-sponsor-modal">
			<button class="close-modal js-close-modal">
				<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 612 612" style="enable-background:new 0 0 612 612;" xml:space="preserve">
					<g>
						<polygon points="612,36.004 576.521,0.603 306,270.608 35.478,0.603 0,36.004 270.522,306.011 0,575.997 35.478,611.397 306,341.411 576.521,611.397 612,575.997 341.459,306.011"/>
					</g>
				</svg>
			</button>
			<div class="decor-cross">
				<img src="img/many_cross.png" alt="">
			</div>
			<div class="inner-container become-sponsor-inner">
				<div class="modal-content">
					<div class="modal-title">Become a Sponsor</div>
					<div class="modal-pre-text">Leave your information below and we’ll provide you with information about sponsorship packages as soon as we can.</div>
					<form action="" class="modal-form">
						<div class="modal-form-row become-sponsor-modal-row">
							<span class="modal-form-input-title">Name</span>
							<input type="text" class="modal-form-input">
						</div>
						<div class="modal-form-row become-sponsor-modal-row">
							<span class="modal-form-input-title">Last Name</span>
							<input type="text" class="modal-form-input">
						</div>
						<div class="modal-form-row become-sponsor-modal-row">
							<span class="modal-form-input-title">Email</span>
							<input type="text" class="modal-form-input">
						</div>
						<div class="modal-form-row become-sponsor-modal-row">
							<span class="modal-form-input-title">Company</span>
							<input type="text" class="modal-form-input">
						</div>
						<div class="modal-form-row become-sponsor-modal-row">
							<span class="modal-form-input-title">Title</span>
							<input type="text" class="modal-form-input">
						</div>
						<div class="modal-form-row become-sponsor-modal-row">
							<span class="modal-form-input-title">Message</span>
							<input type="text" class="modal-form-input">
						</div>
						<button type="submit" class="btn-green-2">Send request</button>
					</form>
				</div>
				<img src="img/statue_lion.png" alt="Byzantium #Lion">
			</div>
		</div>
		<!-- modal -->
		<div class="modal contact-modal">
			<button class="close-modal js-close-modal">
				<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 612 612" style="enable-background:new 0 0 612 612;" xml:space="preserve">
					<g>
						<polygon points="612,36.004 576.521,0.603 306,270.608 35.478,0.603 0,36.004 270.522,306.011 0,575.997 35.478,611.397 306,341.411 576.521,611.397 612,575.997 341.459,306.011"/>
					</g>
				</svg>
			</button>
			<div class="decor-cross">
				<img src="img/many_cross.png" alt="">
			</div>
			<div class="inner-container contact-inner">
				<div class="modal-content">
					<div class="modal-title">Contact</div>
					<div class="modal-pre-text">Got a question? We’d love to hear from you. Send us a message and we’ll respond as soon as possible.</div>
					<form action="" class="modal-form">
						<div class="modal-form-row contact-modal-row">
							<span class="modal-form-input-title">Name</span>
							<input type="text" class="modal-form-input">
						</div>
						<div class="modal-form-row contact-modal-row">
							<span class="modal-form-input-title">Email</span>
							<input type="text" class="modal-form-input">
						</div>
						<div class="modal-form-row contact-modal-row">
							<span class="modal-form-input-title">Message</span>
							<input type="text" class="modal-form-input">
						</div>
						<button type="submit" class="btn-green-2">Send message</button>
					</form>
				</div>
				<img src="img/statue_lion.png" alt="Byzantium #Lion">
			</div>
		</div>
		<!-- modal -->
		<div class="modal thank-you-modal">
			<button class="close-modal js-close-modal">
				<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 612 612" style="enable-background:new 0 0 612 612;" xml:space="preserve">
					<g>
						<polygon points="612,36.004 576.521,0.603 306,270.608 35.478,0.603 0,36.004 270.522,306.011 0,575.997 35.478,611.397 306,341.411 576.521,611.397 612,575.997 341.459,306.011"/>
					</g>
				</svg>
			</button>
			<div class="inner-container thank-you-modal-inner">
				<div class="modal-content">
					<div class="modal-title">Thanks, we’ll be in touch shortly</div>
					<div class="modal-pre-text">Someone on our team is reviewing your request and will contact with you as soon as possible.</div>
				</div>
				<img src="img/statue_thank-you.png" alt="Byzantium #Thanks" class="modal-statue-thank-you-img">
			</div>
		</div>


		<!-- <script src="libs/jquery/dist/jquery.min.js"></script> -->
		<script src="js/libs.min.js"></script>
		<script src="js/common.js"></script>
	</body>
</html>